name: perl critic
on: [push]
jobs:
  perltidy:
    runs-on: ubuntu-latest
    container:
      image: perl:5.32
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: cpanm -n Perl::Tidy
      - name: perltidy --version
        run: perltidy --version
      - name: Run perltidy
        shell: bash
        run: |
          shopt -s extglob globstar nullglob
          perltidy --pro=.../.perltidyrc -b -bext='/' **/*.p[lm] **/*.t && git diff --exit-code
  perlcritic:
    runs-on: ubuntu-latest
    steps:
      - name: gugod-perlcritic (with reviewdog)
        uses: gugod/action-perlcritic@fun
