name: Super Linter
on: [push]
jobs:
  superlinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v4.8.1
        env:
          DEFAULT_BRANCH: master
          USE_FIND_ALGORITHM: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
