name: BuildTest0hy.esContainer
on:
  pull_request:
    branches: [ stage ]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          docker build -t ${{ github.repository }} --load . 
      -
        name: imageList
        run: |
          docker image ls
      -
        name: Run
        run: |
          docker run -d -p80:80 ${{ github.repository }}
      -
        name: dockerPS
        run: |
          docker ps
      -
        name: Sleep
        run: |
          sleep 60
      -
        name: testTides
        run: |
          curl -L http://127.0.0.1/tides | grep UPDATED
      -
        name: testMainPage
        run: |
          curl -L http://127.0.0.1 | grep -w 0hy.es
